import React, { useState, useEffect } from 'react';
import { api } from '../../../services/api';
import { patientService } from '../../../services/patientService'; // Use for list fetching mock
import { GlassCard, Button, Badge, Loader, Modal } from '../../../components/UI';
import { Brain, FileText, ArrowLeft, ShieldCheck, AlertCircle } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../../../context/AuthContext';

const AIInsightCard: React.FC<{ doc: any }> = ({ doc }) => {
  const [open, setOpen] = useState(false);
  const [ai, setAI] = useState<any>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const loadInsight = async () => {
    setLoading(true);
    setError('');
    try {
      const data = await api.get<any>(`/clinical/documents/${doc.id}/ai`);
      setAI(data);
      setOpen(true);
    } catch (err: any) {
        // Mock fallback for UI demo if backend lacks specific doc data during dev
        if (doc.extractedData) {
            setAI({
                summary: doc.extractedData.summary,
                highlights: doc.extractedData.diagnosis || [],
                recommendations: ["Consult primary care physician."],
                source: "AI-assisted Analysis (Cached)"
            });
            setOpen(true);
        } else {
            setError('AI Insight not available for this document.');
        }
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
        <GlassCard className="flex flex-col md:flex-row justify-between items-center gap-4 group hover:border-teal/30 transition-all">
            <div className="flex items-center gap-4">
                <div className="p-3 bg-purple/10 rounded-lg text-purple group-hover:bg-purple group-hover:text-white transition-colors">
                    <Brain size={24} />
                </div>
                <div>
                    <h3 className="text-white font-bold">{doc.title}</h3>
                    <p className="text-xs text-text-secondary">{new Date(doc.date).toLocaleDateString()} • {doc.type}</p>
                </div>
            </div>
            
            <Button 
                variant="outline" 
                className="text-xs" 
                onClick={loadInsight}
                disabled={loading}
                icon={loading ? <Loader text="" /> : <Brain size={14} />}
            >
                {loading ? 'Analyzing...' : 'View AI Summary'}
            </Button>
        </GlassCard>

        {/* Insight Modal */}
        <Modal isOpen={open} onClose={() => setOpen(false)} title="AI Document Summary">
            {ai && (
                <div className="space-y-6">
                    <div className="p-4 bg-teal/5 border border-teal/20 rounded-lg">
                        <h4 className="text-teal font-bold mb-2 flex items-center gap-2">
                             <FileText size={16} /> Summary
                        </h4>
                        <p className="text-white text-sm leading-relaxed">{ai.summary}</p>
                    </div>

                    {ai.highlights && ai.highlights.length > 0 && (
                        <div>
                            <h5 className="text-xs text-text-secondary uppercase tracking-wider mb-2">Key Highlights</h5>
                            <div className="flex flex-wrap gap-2">
                                {ai.highlights.map((h: string, i: number) => (
                                    <Badge key={i} color="purple">{h}</Badge>
                                ))}
                            </div>
                        </div>
                    )}

                    {ai.recommendations && (
                        <div className="space-y-2">
                             <h5 className="text-xs text-text-secondary uppercase tracking-wider">Recommendations</h5>
                             <ul className="list-disc pl-5 text-sm text-text-secondary space-y-1">
                                {ai.recommendations.map((r: string, i: number) => (
                                    <li key={i}>{r}</li>
                                ))}
                             </ul>
                        </div>
                    )}

                    <div className="pt-4 border-t border-white/10 flex flex-col gap-2">
                        <div className="flex items-center gap-2 text-[10px] text-text-secondary">
                            <ShieldCheck size={12} className="text-teal"/> Source: {ai.source}
                        </div>
                        <p className="text-[10px] text-text-secondary italic bg-black/30 p-2 rounded">
                            Disclaimer: This summary is generated by AI for informational purposes only and does not constitute a medical diagnosis. Always consult your doctor for professional advice.
                        </p>
                    </div>
                </div>
            )}
        </Modal>
        
        {/* Error Toast / Alert (Inline for simplicity) */}
        {error && (
            <div className="mt-2 text-xs text-red-400 flex items-center gap-2 bg-red-500/10 p-2 rounded">
                <AlertCircle size={12} /> {error}
            </div>
        )}
    </>
  );
};

export const AIInsights: React.FC = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [docs, setDocs] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDocs = async () => {
        if(user) {
            const records = await patientService.getRecords(user.id);
            // Filter only docs that might have AI data (simulated by having extractedData in mock)
            setDocs(records.filter(r => r.extractedData || r.type === 'Lab Report'));
        }
        setLoading(false);
    };
    fetchDocs();
  }, [user]);

  return (
    <div className="max-w-4xl mx-auto p-6 space-y-6">
        <div className="flex justify-between items-center">
            <div>
                 <Button variant="outline" className="text-xs !py-1 !px-2 mb-2" onClick={() => navigate('/dashboard')} icon={<ArrowLeft size={12}/>}>Dashboard</Button>
                 <h1 className="text-2xl font-display font-bold text-white">AI Clinical Insights</h1>
                 <p className="text-text-secondary text-sm">Automated summaries of your medical history.</p>
            </div>
        </div>

        {loading ? (
             <div className="flex justify-center py-20"><Loader text="Loading insights..." /></div>
        ) : docs.length === 0 ? (
             <div className="text-center py-16 border border-dashed border-white/10 rounded-xl">
                 <Brain className="mx-auto text-text-secondary mb-4 opacity-50" size={48} />
                 <p className="text-text-secondary">No AI-processed documents found.</p>
                 <Button variant="outline" className="mt-4" onClick={() => navigate('/dashboard/records')}>Upload Record</Button>
             </div>
        ) : (
            <div className="space-y-4">
                {docs.map(doc => (
                    <AIInsightCard key={doc.id} doc={doc} />
                ))}
            </div>
        )}
    </div>
  );
};
